### ISSUE TITLE
The :let-heredoc feature isn't supported

### ISSUE THREAD

**Issue by jchros** [vigoux/tree-sitter-viml#101]
Using [the example from help](https://github.com/vim/vim/blob/2e693a88b24dc6b12883fad78ff2cb9cd4469c98/runtime/doc/eval.txt#L11412-L11421):

```vim
let var1 =<< END
Sample text 1
    Sample text 2
Sample text 3
END

let data =<< trim DATA
	1 2 3 4
	5 6 7 8
DATA
```

## Possible output syntax tree

```
(let_statement
  (identifier)
  (heredoc
    (heredoc_endmarker)
    (heredoc_body)
    (heredoc_endmarker)))

(let_statement
  (identifier)
  (heredoc
    (heredoc_options)
    (heredoc_endmarker)
    (heredoc_body)
    (heredoc_endmarker)))
```

Or as an output of tree-sitter's playground:

```
let_statement [0, 0] - [4, 3]
  identifier [0, 4] - [0, 8]
  heredoc [0, 13] - [4, 3]
    heredoc_endmarker [0, 13] - [0, 16]
    heredoc_body [1, 0] - [3, 13]
    heredoc_endmarker [4, 0] - [4, 3]
let_statement [6, 0] - [9, 4]
  identifier [6, 4] - [6, 8]
  heredoc_options [6, 13] - [6, 17]
  heredoc_endmarker [6, 18] - [6, 22]
  heredoc_body [7, 0] - [8, 8]
  heredoc_endmarker [9, 0] - [9, 4]
```

## Current output syntax tree

```
let_statement [0, 0] - [0, 3]
ERROR [0, 4] - [0, 16]
  identifier [0, 4] - [0, 8]
  keyword [0, 13] - [0, 16]
user_command [1, 0] - [1, 13]
  command_name [1, 0] - [1, 6]
  arguments [1, 7] - [1, 13]
    command_argument [1, 7] - [1, 11]
    command_argument [1, 12] - [1, 13]
user_command [2, 4] - [2, 17]
  command_name [2, 4] - [2, 10]
  arguments [2, 11] - [2, 17]
    command_argument [2, 11] - [2, 15]
    command_argument [2, 16] - [2, 17]
user_command [3, 0] - [3, 13]
  command_name [3, 0] - [3, 6]
  arguments [3, 7] - [3, 13]
    command_argument [3, 7] - [3, 11]
    command_argument [3, 12] - [3, 13]
user_command [4, 0] - [4, 3]
  command_name [4, 0] - [4, 3]
let_statement [6, 0] - [6, 3]
ERROR [6, 4] - [8, 8]
  identifier [6, 4] - [6, 8]
  keyword [6, 13] - [6, 17]
  keyword [6, 18] - [6, 22]
user_command [9, 0] - [9, 4]
  command_name [9, 0] - [9, 4]
```

**Comment by catlee** [comment]
Similar to this, :lua-heredoc isn't supported either.

```vim
lua << EOF
...
EOF
```

**Comment by jchros** [comment]
By inspecting the source code, it seems there is some code written to handle heredocs for `:lua`, `:ruby`, `:python`, and `:perl` ([here](https://github.com/vigoux/tree-sitter-viml/blob/4b9d2dda6de64fe5abc9bf96b5727ba73ed08515/src/scanner.c#L277-L311)).  However, that code is never called.

**Comment by vigoux** [comment]
> By inspecting the source code, it seems there is some code written to handle heredocs for `:lua`, `:ruby`, `:python`, and `:perl` ([here](https://github.com/vigoux/tree-sitter-viml/blob/4b9d2dda6de64fe5abc9bf96b5727ba73ed08515/src/scanner.c#L277-L311)). However, that code is never called.

Looking at the code (an knowing it :wink:) this is actuall called [here](https://github.com/vigoux/tree-sitter-viml/blob/4b9d2dda6de64fe5abc9bf96b5727ba73ed08515/src/scanner.c#L566).

There is issues with this part of the code though, and that makes problems (https://github.com/vigoux/tree-sitter-viml/issues/80), so errors about this should be reported into that other issue (which should, then, be reopened)
