### ISSUE TITLE
Lua injection fails after `2dbe41988636062fe5c00aefe75a47a4d849d9d2`

### ISSUE THREAD

**Issue by lmburns** [vigoux/tree-sitter-viml#111]
In my Neovim configuration I have several files with something like the following:

```lua
cmd [[
  syn match qfFileName /^[^│]*/ nextgroup=qfSeparatorLeft
  syn match qfSeparatorLeft /│/ contained nextgroup=qfLineNr
  syn match qfLineNr /[^│]*/ contained nextgroup=qfSeparatorRight
  syn match qfSeparatorRight '│' contained nextgroup=qfError,qfWarning,qfInfo,qfNote
  syn match qfError / E .*$/ contained
  syn match qfWarning / W .*$/ contained
  syn match qfInfo / I .*$/ contained
  syn match qfNote / [NHZ] .*$/ contained


  hi def link qfFileName Function
  hi def link qfSeparatorLeft Delimiter
  hi def link qfSeparatorRight Delimiter
  hi def link qfLineNr LineNr
  hi def link qfError CocErrorSign
  hi def link qfWarning CocWarningSign
  hi def link qfInfo CocInfoSign
  hi def link qfNote CocHintSign
]]
```

When adding `vim.` in front of `cmd`, I get the following error:

```
Error executing vim.schedule lua callback: ...-linux64/share/nvim/runtime/lua/vim/treesitter/query.lua:174: query: invalid stru
cture at position 23
stack traceback:
        [C]: in function '_ts_parse_query'
        ...-linux64/share/nvim/runtime/lua/vim/treesitter/query.lua:174: in function 'get_query'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:36: in function 'new'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:210: in function 'add_child'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:142: in function 'parse'
        ...ker/start/nvim-treesitter/lua/nvim-treesitter/indent.lua:75: in function 'get_indent'
        .../opt/indent-blankline.nvim/lua/indent_blankline/init.lua:466: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

When reverting to [`nvim-treesitter`](https://github.com/nvim-treesitter/nvim-treesitter)'s commit [`116c72f`](https://github.com/nvim-treesitter/nvim-treesitter/commit/116c72f5c2e4e63bbf0b7d698f9d35e36848605a), everything works just as it had before. A change that was made in that commit was to change this parser's revision to the commit mentioned in the title of this issue.

Before this commit, the injections were displayed correctly.

I have tried using single quotes, double quotes, double bracket (`[[]]`), using the `vim.cmd` command on one line, i.e., something like `vim.cmd("abo lw")`, but all of them fail. I have also tried erasing my own custom queries I have for Lua but it doesn't seem to do anything.

Editing to say that both `vim.api.nvim_command` and `vim.api.nvim_exec` don't work either. All of the following fail:
```lua
vim.cmd("packadd packer.nvim")
vim.cmd([[packadd packer.nvim]])
vim.cmd('packadd packer.nvim')
vim.api.nvim_command("packadd packer.nvim")
vim.api.nvim_exec("packadd packer.nvim")
```

**Comment by vigoux** [comment]
Hi, did you run `TSUpdate` when updating you neovim configuration?
The queries are guaranteed to work (ensured in CI) so I am pretty sure it comes from your end

**Comment by lmburns** [comment]
Yeah I did run `:TSUpdate`. I have a hook to run automatically. I just ran it again to make sure and I still get the same error. I'm not sure how to debug this. The error message isn't that helpful. I'll start by searching for `CursorMoved` autocommands and will comment back here.

The last two lines in the error are plugin related. Though I don't believe this has anything to do with a specific plugin. As the plugin in the first error I gave on this thread had to do with `indent-blankline.nvim` and the one below mentions `nvim_context_vt`. Each of these plugins are treesitter related though.

```
Error detected while processing CursorMoved Autocommands for "*":
E5108: Error executing lua ...-nightly/share/nvim/runtime/lua/vim/treesitter/query.lua:174: query: invalid structure
 at position 23
stack traceback:
        [C]: in function '_ts_parse_query'
        ...-nightly/share/nvim/runtime/lua/vim/treesitter/query.lua:174: in function 'get_query'
        ...y/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:36: in function 'new'
        ...y/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:210: in function 'add_child'
        ...y/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:142: in function 'parse'
        ...neovim-nightly/share/nvim/runtime/lua/vim/treesitter.lua:72: in function '_create_parser'
        ...neovim-nightly/share/nvim/runtime/lua/vim/treesitter.lua:98: in function 'get_parser'
        ...r/start/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:163: in function 'get_node_at_cursor'
        ...packer/opt/nvim_context_vt/lua/nvim_context_vt/utils.lua:44: in function 'find_virtual_text_nodes'
        .../packer/opt/nvim_context_vt/lua/nvim_context_vt/init.lua:54: in function 'show_context'
        [string ":lua"]:1: in main chunk
```

**Comment by lmburns** [comment]
I found out this has to do with the plugin `vim-matchup`. It was causing this issue.

**Comment by vigoux** [comment]
For the future: I think you should be careful about where you open the issues.
Most of the time these issues (of query errors and such) come from `nvim-treesitter`.
