### ISSUE TITLE
Quoted rhs in <expr> mappings are highlighted as comments

### ISSUE THREAD

**Issue by gpanders** [vigoux/tree-sitter-viml#13]
In the following mapping

```vim
nnoremap <expr> [a ":\<C-U>" . v:count1 . "prev\<CR>"
```

the right-hand side is incorrectly parsed as a comment.

**Comment by vigoux** [comment]
Thanks for reporting !

I am looking into that right now.

**Comment by gpanders** [comment]
Thanks! I am looking into it too, but I am very much a tree-sitter noob so it seems likely you will figure it out before I do :)

**Comment by vigoux** [comment]
To be honest, I think that the first thing would be to add basic support for `map` commands

**Comment by vigoux** [comment]
Then go incrementally from here

**Comment by vigoux** [comment]
So, very basic support should have been adding in ee58a76952472bc753813eb31a0e2252893e4cf0 already.
Now we need to add everything that surrounds the mappings:
- Options (like `<expr>`)
- Keycodes (`<CR>` in the sides)
- And all the variants (will be boring AF)

**Comment by vigoux** [comment]
This should have been fixed in the latest commit, closing.
