### ISSUE TITLE
augroup name not parsed correctly

### ISSUE THREAD

**Issue by max397574** [vigoux/tree-sitter-viml#14]
**Describe the bug**

the augroup name isn't parsed correctly

I have an augroup with a `_`in the name. The `_`and the part after it are seen as command and not as name. Perhhaps an error with the regex
![Screen Shot 2021-08-20 at 16 03 03](https://user-images.githubusercontent.com/81827001/130245773-a79051f7-15a2-403b-b5a1-6423313b15bc.png)

**Comment by vigoux** [comment]
Feel free to open issues as you see them, we will do the updates in `nvim-treesitter` by batches/

**Comment by max397574** [comment]
ok
I'll write as soon as I see sth. That's the only way I can support this parser when I finally got added :)
