### ISSUE TITLE
register operation in mapping is treated as comment

### ISSUE THREAD

**Issue by jdhao** [vigoux/tree-sitter-viml#20]
Related to #13, but IMO, not the same. See the image below:

![](https://user-images.githubusercontent.com/16662357/130344009-72cd9cd0-dfd0-4907-944b-3888d7f6cf18.png)

**Comment by jdhao** [comment]
Also the highlights for some commands are missing in the above image.

**Comment by vigoux** [comment]
Known issue, I am working on fixing it, should have a fix by today.

**Comment by vigoux** [comment]
Should have been fixed by b37f5ac645d3db1f5ef9c9b07f12d760fadc038d
