### ISSUE TITLE
String literal argument for "syntax match" command is parsed as comment

### ISSUE THREAD

**Issue by 0xAdk** [vigoux/tree-sitter-viml#22]
how it looks:
![image](https://user-images.githubusercontent.com/29005635/130852526-f074241c-8491-4a5a-9fbe-7637d4ab7113.png)

codesnippet + tree:
```vim
syn match MatchGroup "this should be a string literal" skipwhite
```
```
command [0, 0] - [1, 0]                 | syn
  command_name [0, 0] - [0, 3]          | match MatchGroup1
  arguments [0, 4] - [0, 20]
    command_argument [0, 4] - [0, 9]
    command_argument [0, 10] - [0, 20]
  comment [0, 21] - [0, 64]             | "this should be a string literal" skipwhite
``` 

found this bug while looking at the [tags.vim](https://github.com/neovim/neovim/blob/master/runtime/syntax/tags.vim) syntax file

**Comment by vigoux** [comment]
Should have been fixed in latest master.
