### ISSUE TITLE
Lines with "=" followed by a number break detection of comment further ahead in the same line

### ISSUE THREAD

**Issue by lokesh-krishna** [vigoux/tree-sitter-viml#24]
![grim-2021-08-28-12-19-42](https://user-images.githubusercontent.com/20235646/131209948-540398bc-66f4-48ca-865a-0552408c798f.png)

Confirmed that things work as expected with treesitter disabled

**Comment by stsewd** [comment]
Can you share the file you are using? I'm not able to replicate this with

```vim
set scrolloff=7  " A comment
```

Also, make sure you are using the latest version of the parser `:TSUpdate`

**Comment by lokesh-krishna** [comment]
It's just my `init.vim`: [init.vim](https://gist.github.com/lokesh-krishna/54dfa014423f310d3f24a697623f6f2d)

**Comment by vigoux** [comment]
There has been a fx for error related to`set` a few days ago, I am not sure they are merged in `nvim-treesitter` already.

**Comment by lokesh-krishna** [comment]
Just updated `nvim-treesitter` and ran `TSUpdate` but didn't get anything new for viml. How can I keep track?

**Comment by stsewd** [comment]
I'm able to replicate this with

```
set scrolloff=7				" show 7 lines around the cursorline
```

The comment is separated by tabs, that's confusing the parser.

**Comment by vigoux** [comment]
Good to know, I never really tested things with tabs, will fix this and add it to the test base

**Comment by vigoux** [comment]
Got a fix, pushing in a few minutes.

**Comment by lokesh-krishna** [comment]
Thanks! This will only come into effect after nvim-treesitter itself has been updated, right? Or would running TSUpdate after you've pushed the change do it?

**Comment by vigoux** [comment]
We'll need to pull the update in nvim-treesitter itself first, let me make that a thing.

**Comment by lokesh-krishna** [comment]
Could you ping here once it's in?

**Comment by lokesh-krishna** [comment]
Didn't think it was worth opening a new issue but adding a space before the equal sign, like:

```
set scrolloff =7				" show 7 lines around the cursorline

```

Does result in the comment not getting highlighted while it does get appropriately highlighted with treesitter disabled.

**Comment by vigoux** [comment]
Should have been fixed in nvim-treesitter already
