### ISSUE TITLE
Parse error for inline "if | map [...] | endif" statement

### ISSUE THREAD

**Issue by milisims** [vigoux/tree-sitter-viml#27]
``` vim
if a | nnoremap b c | endif
```
parses to
```
ERROR [1, 0] - [2, 0]
  identifier [1, 3] - [1, 4]
  map_statement [1, 7] - [2, 0]
    lhs: map_side [1, 16] - [1, 17]
    rhs: map_side [1, 17] - [1, 27]
```
This works fine:
``` vim
if a | nnoremap b c
endif
```
=>
```
if_statement [1, 0] - [3, 0]
  condition: identifier [1, 3] - [1, 4]
  body [1, 7] - [2, 0]
    map_statement [1, 7] - [2, 0]
      lhs: map_side [1, 16] - [1, 17]
      rhs: map_side [1, 17] - [1, 19]
```
Sorry, made the issue then tested more things.

Seems to be an issue with mapping, it doesn't happen with, for example, `echo`.

**Comment by vigoux** [comment]
Hi, after looking into the docs it seems I misinterpreted it, and that, in the case of a mapping, you can have another command with a `|` in the `rhs`.

I'll see if I can fix that at some point, but can't guarantee anything.
