### ISSUE TITLE
Nodes include EOL chars

### ISSUE THREAD

**Issue by stsewd** [vigoux/tree-sitter-viml#28]
```vim
let foo = "bar"
```

```
$ npm run parse -- test.vim

(script_file [0, 0] - [1, 0]
  (let_statement [0, 0] - [1, 0]
    (identifier [0, 4] - [0, 7])
    (string_literal [0, 10] - [0, 15])))
```

As you can see the script file and let_statement nodes put the end at the "next" line, aka `EOL` char, instead of having the end at `[0, 15]`.

This is because of the `_cmd_separator` is included at the end of every line/sentence https://github.com/vigoux/tree-sitter-viml/blob/59595443fb486449f42db839934117221358a85f/grammar.js#L135-L141

that node should be always be advanced as `advance(lexer, true)`, but there is more code to change for that works.

**Comment by vigoux** [comment]
Did you try making the changes that you propose ?

**Comment by stsewd** [comment]
> Did you try making the changes that you propose ?

yeah, but that caused an infinite loop somewhere, so this needs some other changes in the grammar, but didn't dig enough yet.

**Comment by vigoux** [comment]
Okay, following a recent refactor of the parser, this has actually been fixed in latest master.

**Comment by vigoux** [comment]
For the record, the new version of the tree is the following:
```
(script_file [0, 0] - [1, 0]
  (let_statement [0, 0] - [0, 15]
    (identifier [0, 4] - [0, 7])
    (string_literal [0, 10] - [0, 15])))
```
