### ISSUE TITLE
Bad highlighting of set keyword when following `\` for a space in statusline

### ISSUE THREAD

**Issue by David-Else** [vigoux/tree-sitter-viml#38]
```
set statusline+=%m\
set statusline+=%=
```
![Screenshot from 2021-11-28 17-45-07](https://user-images.githubusercontent.com/12832280/143779572-5f8ae8b5-c1c5-47b8-9b98-0b37f6b12a1d.png)

**Comment by vigoux** [comment]
Thanks for reporting, this should be fixed in master soon.
