### ISSUE TITLE
No highlighting with modifiers without spaces in maps

### ISSUE THREAD

**Issue by carlosala** [vigoux/tree-sitter-viml#39]
Hi!

This looks simple to improve, when there are multiple modifiers in the map (such as `<script>`, `<expr>`, etc) them are not highlighted.
When there is one, all ok.
I put here an example to illustrate it:
```vim
nmap <silent> <M-CR> doSomething() " highlighted
nmap <silent><expr> <M-CR> doSomething() " not highlighted
```

Thanks, and nice work with the tree-sitter plugin!

**Comment by stsewd** [comment]
I had this problem another time, this is because the parser requires a space between the modifiers

```
nmap <silent> <expr> <M-CR> doSomething() " not highlighted
```

but maybe it is an easy fix.

**Comment by carlosala** [comment]
I see that works like that, but I think the parser should support all options.

**Comment by vigoux** [comment]
Changing the title to reflect the actual error.

**Comment by carlosala** [comment]
@vigoux the error is without the space, not with the space

**Comment by vigoux** [comment]
Oh, right

**Comment by Fymyte** [comment]
In my testing, it seems that the mentionned issue has been fixed.
They were another issue here with the `<M-CR>` mapping which should be fixed with be above mentioned PR.

**Comment by carlosala** [comment]
Yes, it looks fixed!
