### ISSUE TITLE
No highlighting on string command arguments

### ISSUE THREAD

**Issue by ckuchimanchi** [vigoux/tree-sitter-viml#40]
Hello there,

Thanks for this project :) I'm a tree sitter noob here, so this may not be an issue at all. 

I've noticed that string parameters to command arguments are not highlighted, where as they do get highlighted when passed as arguments to function calls. 

To me, this is unexpected. Attached is the screenshot (with default neovim theme)

![image](https://user-images.githubusercontent.com/7849452/148219266-2a9e36ca-c01d-4221-8b0d-d367bc0ebd66.png)

Is this a known issue? 

Thanks again!

**Comment by vigoux** [comment]
Hi, and thanks for reporting !
First of all, the question of parsing user commands argument is interesting, and the choice made by vim is actually weird.

When writing vimscript, the command arguments can actually be anything, it is up to the command itself to parse it's arguments. Thus being 100% sure that this is a string (I assue you as talking about `Plug` instances), is actually impossible.

BUT the fact that vim does that should indicate us something, so I'll add some test for this and support for it in a sec.
