### ISSUE TITLE
error on `set foldexpr`

### ISSUE THREAD

**Issue by doubleloop** [vigoux/tree-sitter-viml#41]
```vim
set foldexpr=nvim_treesitter#foldexpr()
```

```
set_statement [26, 0] - [27, 0]
  set_item [26, 4] - [26, 39]
    option: option_name [26, 4] - [26, 12]
    value: set_value [26, 13] - [26, 39]
      ERROR [26, 13] - [26, 39]
        identifier [26, 13] - [26, 37]
```

Note: other values mentioned in `:h fold-expr` examples also produce errors

**Comment by vigoux** [comment]
Hi, this might be caused by the `#` symbol, but I am not sure yet.

**Comment by vigoux** [comment]
Hey I can't seem to reproduce this issue in latest master for some reason, could you check that is disapeared for you too.
I added tests to ensure that this behavior is kept though.
