### ISSUE TITLE
Many commands break highlight

### ISSUE THREAD

**Issue by yanzhang0219** [vigoux/tree-sitter-viml#48]
1. `colorscheme`

<img width="688" alt="image" src="https://user-images.githubusercontent.com/11582667/149708752-be3ba2d2-08e5-404f-b654-adaff349e418.png">

2. `autocmd VimResized * wincmd =`

<img width="824" alt="image" src="https://user-images.githubusercontent.com/11582667/149708817-97eed08e-024e-49fe-8683-84b5672ec8b8.png">

3. `xnoremap < <gv`

<img width="319" alt="image" src="https://user-images.githubusercontent.com/11582667/149708856-172064bc-456d-4146-80ee-9c4b5097bd52.png">

4. `runtime macros/matchit.vim`

<img width="475" alt="image" src="https://user-images.githubusercontent.com/11582667/149709352-0bc4d6dc-edf1-446e-8067-2f1d786726be.png">

5. `command!`

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/11582667/149709432-2b15db8d-4b37-41b6-b7b3-1448030036ea.png">

Thank you very much.

**Comment by vigoux** [comment]
Thanks for reporting, I'll use this issue to track the progress we make on the various built-in commands implementation.

**Comment by Luminiscental** [comment]
Adding on to this, using `syn keyword` with arguments like `cchar=&` or `containedin=cComment` seems to break:

![Screenshot 2022-01-20 11-36-05](https://user-images.githubusercontent.com/16429289/150331666-0bfadaf9-b174-4893-8c7b-a1616b87c721.png)

**Comment by vigoux** [comment]
The `syntax` command support is pretty fresh and has not landed in `nvim-treesitter`. So are you sure that the version you refer to in your example is current master ?

**Comment by Luminiscental** [comment]
> The syntax command support is pretty fresh and has not landed in nvim-treesitter. So are you sure that the version you refer to in your example is current master?

Ah, yes this is my issue, thanks!

**Comment by syphar** [comment]
I discovered another issue where highlighting stops with vimscript: 
```vim
augroup packer_user_config
    autocmd!
    autocmd BufWritePost plugins.lua source <afile> | PackerCompile
augroup end
```

Everything after `source`, including `augroup end` is unstyled. 

In the generated tree there is an `ERROR`, which makes me think that there is an issue with the parser (from the treesitter playground): 
```
augroup_statement [0, 0] - [1, 0]
  augroup_name [0, 8] - [0, 26]
autocmd_statement [1, 4] - [1, 12]
  bang [1, 11] - [1, 12]
autocmd_statement [2, 4] - [2, 11]
ERROR [2, 12] - [3, 11]
  au_event_list [2, 12] - [2, 24]
    au_event [2, 12] - [2, 24]
  pattern [2, 25] - [2, 36]
  identifier [2, 37] - [2, 43]
  identifier [2, 45] - [2, 50]
  identifier [2, 54] - [2, 67]
  identifier [3, 0] - [3, 7]
  identifier [3, 8] - [3, 11]
``` 

If this should be fixed on master I can dig into how I can test this locally

**Comment by Fymyte** [comment]
@syphar can you test this again ? I've checked this using the latest parser and I think it has been fixed
```vim
augroup packer_user_config
    autocmd!
    autocmd BufWritePost plugins.lua source <afile> | PackerCompile
augroup end
```
seems to become
```
augroup_statement [6, 0] - [6, 26]
  augroup_name [6, 8] - [6, 26]
autocmd_statement [7, 4] - [7, 12]
  bang [7, 11] - [7, 12]
autocmd_statement [8, 4] - [8, 51]
  au_event_list [8, 12] - [8, 24]
    au_event [8, 12] - [8, 24]
  pattern [8, 25] - [8, 36]
    term [8, 25] - [8, 36]
      pattern_character [8, 25] - [8, 26]
      pattern_character [8, 26] - [8, 27]
      pattern_character [8, 27] - [8, 28]
      pattern_character [8, 28] - [8, 29]
      pattern_character [8, 29] - [8, 30]
      pattern_character [8, 30] - [8, 31]
      pattern_character [8, 31] - [8, 32]
      any_character [8, 32] - [8, 33]
      pattern_character [8, 33] - [8, 34]
      pattern_character [8, 34] - [8, 35]
      pattern_character [8, 35] - [8, 36]
  command: range_statement [8, 36] - [8, 51]
    start: pattern [8, 36] - [8, 51]
user_command [8, 53] - [8, 67]
  command_name [8, 53] - [8, 67]
augroup_statement [9, 0] - [9, 11]
  augroup_name [9, 8] - [9, 11]
```

**Comment by syphar** [comment]
> @syphar can you test this again ? I've checked this using the latest parser and I think it has been fixed

@Fymyte sorry for the late reply. 

Yes, after updating the parser it works now. 

Thank you for the fix!

**Comment by reegnz** [comment]
I'd add to the pile here by saying `const` is also not defined.

**Comment by Fymyte** [comment]
@reegnz Do you think you can open a new issue ? It would allow us to better distinguish what is done from what's left

**Comment by rockyzhang24** [comment]
Hello @vigoux 

Found some new highlight issues regarding `map`:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/11582667/157296904-1d2c0367-5197-4571-9367-4670bdfbc467.png">

<img width="146" alt="image" src="https://user-images.githubusercontent.com/11582667/157296943-8b2064ef-8049-4578-85a9-68eeea6456c8.png">

<img width="634" alt="image" src="https://user-images.githubusercontent.com/11582667/157296996-278fb71e-bde5-4362-824e-dbb1c4e6ba0e.png">

<img width="634" alt="image" src="https://user-images.githubusercontent.com/11582667/157297055-cc7f8be8-44ff-40df-8ebc-261235249b27.png">

<img width="896" alt="image" src="https://user-images.githubusercontent.com/11582667/157297108-8d1ab9b7-f6f6-43c6-aca9-3bd0fe9ed06e.png">

Thank you very much.

**Comment by vigoux** [comment]
Hi, map is being worked on, and some fixes landed recently, could you tell us if you still encounter this issue ?
