### ISSUE TITLE
Add support for optional function arguments

### ISSUE THREAD

**Issue by reegnz** [vigoux/tree-sitter-viml#54]
VimL has optional function arguments, but the current grammar doesn't seem to support it.

See `:h optional-function-argument` for details.

tl;dr:

```viml
  function Something(key, value = 10)
     echo a:key .. ": " .. a:value
  endfunction
  call Something('empty')	"empty: 10"
  call Something('key', 20)	"key: 20"
```

**Comment by vigoux** [comment]
Hi, and thanks for reporting this, I will be working on this ASAP.
