### ISSUE TITLE
How To Install This

### ISSUE THREAD

**Issue by max397574** [vigoux/tree-sitter-viml#6]
How to I install this in nvim. Or is it recommended not to do so? If so, why?

**Comment by vigoux** [comment]
For now this parser is not ready at all, and I don't have that much time to develop it.
Check nvim-treesitter docs in how to add custom parsers, but I'd suggest that only if you plan to contribute the development of the parser (that is, reporting bugs and such).

**Comment by max397574** [comment]
where can I see when it's ready?

**Comment by max397574** [comment]
@vigoux

**Comment by vigoux** [comment]
> where can I see when it's ready?
> or could I just "try" to use it and report bugs here? (without any knowledge of how it's programmed)

I don't know when it'll be ready, I don't have that much time lately, so I can't guarantee anything. 
Yes you can just try it.
