### ISSUE TITLE
The register '@@' breaks the syntax

### ISSUE THREAD

**Issue by iovis** [vigoux/tree-sitter-viml#69]
When using the unnamed register `@@` in scripts, it seems to error out and breaks highlighting for the rest of the file

Example:
![Screen Shot 2022-02-02 at 17 06 39](https://user-images.githubusercontent.com/6660202/152245431-31118cd5-db1a-4bf7-b8e8-e13e84eee3fe.png)

Commenting out lines with `@@`, brings back the highlighting in the rest of the file.

**Comment by iovis** [comment]
Reproduction code:
```vim
function! SubstituteOperator(type)
  if a:type ==? 'v'
    let isSameLine = getpos("'<")[1] - getpos("'>")[1] == 0

    if isSameLine
      let saved_unnamed_register = @@
      execute 'normal! `<v`>y'
      call feedkeys(':%s/' . escape(@@, '/\') . "//g\<left>\<left>", 't')
      let @@ = saved_unnamed_register
    else
      call feedkeys(":'<,'>s///g\<left>\<left>\<left>", 't')
    endif
  elseif a:type ==# 'char'
    let saved_unnamed_register = @@
    execute 'normal! `[v`]y'
    call feedkeys(':%s/' . escape(@@, '/\') . "//g\<left>\<left>", 't')
    let @@ = saved_unnamed_register
  elseif a:type ==# 'line'
    call feedkeys(":'[,']s///g\<left>\<left>\<left>", 't')
  else
    echo 'TODO: ' . a:type . ' substitute mode'
    return
  endif
endfunction
```

**Comment by Fymyte** [comment]
For some reason `@@` is not documented to access a register in the register help page.
Should be fixed with this PR

**Comment by iovis** [comment]
> For some reason @@ is not documented to access a register in the register help page.
> Should be fixed with this PR

Yeah, I was trying to find it in the vim docs and I had a lot of trouble finding an official mention to it, that's why I didn't include it. I should've said something about it for context, sorry about that.

With `:helpgrep @@` I was able to find the following (in eval.txt):
```
register						*expr-register* *@r*
--------
@r			contents of register 'r'

The result is the contents of the named register, as a single string.
Newlines are inserted where required.  To get the contents of the unnamed
register use @" or @@.  See |registers| for an explanation of the available
registers.

When using the '=' register you get the expression itself, not what it
evaluates to.  Use |eval()| to evaluate it.
```
