### ISSUE TITLE
Lack of highlight

### ISSUE THREAD

**Issue by togetherwhenyouwant** [vigoux/tree-sitter-viml#75]
<img width="399" alt="a62408d43c95d7a0e86aa90b2d6afa2" src="https://user-images.githubusercontent.com/30839204/152725445-78fe9736-6e0b-44ca-9765-b14b292f3105.png">

the colorscheme lack of highlight

**Comment by Fymyte** [comment]
Yes support for this keyword and some others has been added recently and queries for them has not made their way to the nvim-treesitter repo. I'll try to add those today 👍

**Comment by Fymyte** [comment]
@togetherwhenyouwant Queries have been merged on nvim-treesitter, you should get `colorscheme` highlighted as a keyword now
