### ISSUE TITLE
lua statement with endmarker cannot be parsed correctly

### ISSUE THREAD

**Issue by imcaizheng** [vigoux/tree-sitter-viml#80]
### Describe the bug

On a buffer of vim file type, lua statement with endmarker(e.g. `<<EOF`) is parsed wrongly.

### To Reproduce

1. Open a new buffer in nvim, set filetype to `vim`.
2. Write a lua statement on the buffer, for example:

    ``` vim
    lua << EOF
    local test
    EOF
    ```
3. Running `:TSPlaygroundToggle` output:

    ``` tsplayground
    lua_statement [0, 0] - [2, 3]
      script [0, 7] - [2, 3]
        ERROR [0, 7] - [0, 10]
          identifier [0, 7] - [0, 10]
        local_declaration: variable_declaration [1, 0] - [1, 10]
          variable_list [1, 6] - [1, 10]
            name: identifier [1, 6] - [1, 10]
        ERROR [2, 0] - [2, 3]
          identifier [2, 0] - [2, 3]
        chunk [1, 0] - [1, 10]
    ```

### Expected behavior

No syntax errors in the parsing tree.

**Comment by Fymyte** [comment]
I'll see if I can fix this tomorrow

**Comment by vigoux** [comment]
Hi, after further inverstigation, this is an error related to how `nvim-treesitter` write its injection queries. I am closing this then.

**Comment by Terseus** [comment]
@vigoux Since this one is closed now, is there an issue with the root bug that we can follow to track progress?

Maybe https://github.com/nvim-treesitter/nvim-treesitter/issues/2531 should be reopened?
