### ISSUE TITLE
Incorrect short form for endfunction keyword 

### ISSUE THREAD

**Issue by 0xAdk** [vigoux/tree-sitter-viml#82]
according to `:help endfunction` `:endfunction` would range from `:endf` to `:endfunction` but the way it currently is setup 
 it accepts `:end` as it's shortest form. I pretty sure this is a mistake.

https://github.com/vigoux/tree-sitter-viml/blob/79a4a637c1667f2ad60b2c40e93bbd2b4a63c45c/src/scanner.c#L102
https://github.com/vigoux/tree-sitter-viml/blob/79a4a637c1667f2ad60b2c40e93bbd2b4a63c45c/src/scanner.c#L36

**Comment by Fymyte** [comment]
Totally true I'll fix this thanks for the report 👍

**Comment by Fymyte** [comment]
Should be good 👍. Just there is another PR #77 which aims to fix lexing of mandatory part of tokens, so this will still
be buggy as long as the other PR is not merged
