### ISSUE TITLE
Parsing error: `noremap` with `<cmd>`

### ISSUE THREAD

**Issue by clason** [vigoux/tree-sitter-viml#94]
The following (valid) mappings are not parsed correctly:

* `noremap cc :cnext`:
```
ERROR [0, 0] - [0, 17]
  map_side [0, 8] - [0, 10]
  keyword [0, 12] - [0, 17]
```

* `noremap cc <cmd>cnext`:
```
ERROR [0, 0] - [0, 21]
  map_side [0, 8] - [0, 10]
  keycode [0, 11] - [0, 16]
  keyword [0, 16] - [0, 21]
```

**Comment by vigoux** [comment]
Hmm I think they expect a `<CR>` at the end in the parsing process.
I'll fix that and add it as a test.

**Comment by vigoux** [comment]
I am sure that the `noremap cc <cmd>cnext` is simply incorrect (see `:h E5520`).

**Comment by clason** [comment]
Those are minimal examples; the actual examples in my config are correct:

* `nnoremap <leader>cc :cnext<cr>`
* `nnoremap <esc> <cmd>nohlsearch<bar>cclose<cr><esc>`
* `nnoremap <silent> <C-w><C-t> :belowright split <bar> term<CR>`

**Comment by vigoux** [comment]
I think that part of the issue is the missing commands for `cclose` `cnext` and the others like these.

**Comment by clason** [comment]
Ah, that could be! I was banging my head trying to figure out why these are not working, while other seemingly identical ones did...

Is it necessary to hardcode the list of Vim commands in the parser? Wouldn't it simplify things to just allow any string after `:` or `<cmd>`?

**Comment by Fymyte** [comment]
It would be way easier but would not provide the same highlighting. With a simple match of everything we could mark
everything as a string or something like that but with this solution we can show if there is an issue with the command.
The downside is every command has to be parsed manually. There is some discussion about why in #45

**Comment by vigoux** [comment]
To continue with this: parsing "unknown command" as `user_command` for example is a bit trickier than we might think, and might end up in a huge priority headache within the grammar.

One thing we could do is handle most of the `command_name` parsing in the `scanner.c` though, but that too may lead to difficulties.

I'll open a PR with what I have in mind.

**Comment by clason** [comment]
So the latest commit fixed the parsing errors; however, there still remain some (more minor) issues:
* `:cnext` is exposed as `:cnext_statement` so is not captured by the query -- would it make sense to collect all these in a blanket `builtin_statement` so we don't have to add every command individually?
* `<bar>` is not recognized as starting a new command -- I guess it's enough to lump this in with (i.e., treat exactly like) `<cmd>`?

**Comment by vigoux** [comment]
For `:cnext` I'll just add those keywords to the list of keywords (maybe we can autogenerate that too by the way...).

Regarding `<bar>` I think that handling that will be a bit tricky, I'll see what I can do.
